# Site settings
title: Ibnu Maksum
twitter_username: ibnux
name: Ibnu Maksum

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://ibnux.net/
 - title: GitHub
   url: https://github.com/ibnux
 - title: Twitter
   url: http://twitter.com/ibnux
 - title: Linkedin
   url: www.linkedin.com/in/ibnumaksum

#Any buzzword skills you want to include
skills:
 - PHP
 - Golang
 - Python
 - Flutter
 - Microservices
 - Linux
 - Server and Code Security
 - API design
 - Build Automation
 - Project Management
 - Gradle
 - Java
 - Troubleshooting
 - SQL
 - REST
 - Technical Architecture
 - Machine learning
 - Server and Cloud Management

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Head of Software Development
   start: 2019
   end: Ongoing
   employer: PT. Carsworld Digital Indonesia
   description: Dengan team membuat aplikasi Carsworld
 - title: Senior Engineer
   start: 2019
   end: 2019
   employer: PT. Ximpli Multi Solution
   description: Membantu mengatasi masalah yang terjadi dalam pembuatan software
 - title: Senior Engineer
   start: 2018
   end: 2016
   employer: PT. Asia Sarana Telekomunika
   description: Membuat Aplikasi Android

#Education is required
education:
 - level: Diploma 3
   date: 2008
   subject: Teknik Informatika
   school: Politeknik Pos Indonesia

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
#speakerdeck:
#   profileurl: https://speakerdeck.com/ibnux
#   talks:
#    - title: Product Management for Engineers
#      speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
#      conference: API Conference, Berlin 2018
#    - title: Agile Machine Learning - from Theory to Production
#      speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
#      conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
github:
 - ibnux/phpmixbill
 - ibnux/phpmixbill-mikrotik-login-template
 - ibnux/BMKG-importer
 - ibnux/Android-Plat-Nomor-Scanner
 - ibnux/VirtualHostVPN
 - ibnux/php-apk-builder
 - ibnux/Whois.ID
 - ibnux/Waruga

intro: |
  Saya FULL STACK Engineer
  Mengerti membuat Web Aplikasi dan Android Native, serta untuk iOS menggunakan Flutter.
  Mengerti Micro Services dan Serverless
  Mengerti Manage Server baik Dedicated Server, Cloud Service Alibaba, Digital Ocean, AWS, Azure dan Google Cloud.
  Mengerti Jaringan Komputer, Firewall dan produk Mikrotik.
  Mengerti membuat BlockChain dan CrytoCurrency menggunakan CryptoNote ataupun NXT.
  Mengerti keamanan server dan aplikasi.
  Mengerti ElasticSearch dan teman temannya.
  Mengerti Database SQL dan NoSQL
  Senang ngoprek Raspberry Pi
  Mengerti Machine Learning
  Mengerti Chatbot
  I can adapt to new environment and new Technology, i can give solution, i am a troubleshooter, i like to find a bug and fix it, software development is never ending project, always fixing always improving.
  A Company Hire me to manage and control from Frontend to Backend, to make sure all connected.
  I create my own automation for building Android Apps and for deployment
  Mempunyai banyak cicilan, saat ini  cicilan rumah+mobil 11jt/bln :D

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
#additionalinfo: |
#   <strong>Scala</strong>: My current role uses Scala as the primary language and have been building applications in Scala for the last two years. I am familiar with a range of Scala libraries, such as <a target="_blank" href="http://automateddeveloper.blogspot.com/2017/12/an-opinionated-guide-to-building-apis.html"> Akka-Http for building microservices</a> and <a target="_blank" href="http://automateddeveloper.blogspot.com/2018/09/generic-programming-with-scala.html"> Shapeless for generic programming</a>, as well as familiar with a range of <a target="_blank" href="https://basementcrowd.com/2018/11/28/scala-the-aux-pattern-path-dependent-types/" >functional programming techniques available</a>.<br/><br/>